### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by creeper6530** [Kimbatt/torrent-creator#5]
Hi,
I have been trying to download your site for offline use, but nothing works. Only thing that works is loading web page and THEN going offline. That's good, but my browser keeps reloading web pages that I haven't used for a while. Logically, when it tries to reload the webpage, it is offline and due to this it shows "no internet" error. Can you please help me or can you release edited version that I can download to hard disk?
I'm using Windows 10 and Google Chrome.

Please mention me in reply.

**Comment by Kimbatt** [comment]
Hi!
The page will now work when used offline.
The cause of this problem was that web workers (which make the code run multithreaded) only work when the page is loaded over http or https. Now, the page will fall back to the single threaded version when web workers are not available. This can cause the browser to slow down or freeze while creating the torrent file.
Note that you'll also need to download the sha1.js file (which is not downloaded when saving the webpage, because it is dynamically loaded). The easiest way is to clone or  [download](https://github.com/Kimbatt/torrent-creator/archive/refs/heads/gh-pages.zip) the repository.

@creeper6530
