### ISSUE TITLE
Failed to read file: 

### ISSUE THREAD

**Issue by airectx** [Kimbatt/torrent-creator#8]
Error creating torrent in chrome browser(Chrome/105.0.0.0)
![PUQjnt.jpg](https://s6.jpg.cm/2022/09/19/PUQjnt.jpg)
In firefox browser, it works(Firefox/104.0.2)

**Comment by Kimbatt** [comment]
Hi,
This error usually happens when the browser cannot open a file, for example, because it's not readable, or was deleted/renamed after being selected (see [here](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/error_event)).
I've updated it, so it now displays a reason why the file could not be opened.

**Comment by airectx** [comment]
> Hi, This error usually happens when the browser cannot open a file, for example, because it's not readable, or was deleted/renamed after being selected (see [here](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/error_event)). I've updated it, so it now displays a reason why the file could not be opened.

 Hi，
I try to generate the torrent again, getting an error message
```
Failed to read file: [Snow-Raws] 神様はじめました◎ 第06話 (BD 1920x1080 HEVC-YUV420P10 FLACx2).mkv
Reason: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired. (NotReadableError)
```
